# Form implementation generated from reading ui file 'gui_elements\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 451)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 531, 211))
        self.groupBox.setObjectName("groupBox")
        self.txtText = QtWidgets.QTextEdit(parent=self.groupBox)
        self.txtText.setGeometry(QtCore.QRect(10, 20, 511, 181))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txtText.setFont(font)
        self.txtText.setObjectName("txtText")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 270, 531, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.txtCode = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.txtCode.setGeometry(QtCore.QRect(100, 80, 421, 81))
        self.txtCode.setObjectName("txtCode")
        self.lblCode = QtWidgets.QLabel(parent=self.groupBox_2)
        self.lblCode.setGeometry(QtCore.QRect(10, 80, 81, 81))
        self.lblCode.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblCode.setObjectName("lblCode")
        self.lblDictionary = QtWidgets.QLabel(parent=self.groupBox_2)
        self.lblDictionary.setGeometry(QtCore.QRect(10, 20, 81, 41))
        self.lblDictionary.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblDictionary.setObjectName("lblDictionary")
        self.txtDictionary = QtWidgets.QTextEdit(parent=self.groupBox_2)
        self.txtDictionary.setGeometry(QtCore.QRect(100, 20, 421, 41))
        self.txtDictionary.setObjectName("txtDictionary")
        self.btnEncode = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEncode.setGeometry(QtCore.QRect(170, 230, 91, 31))
        self.btnEncode.setObjectName("btnEncode")
        self.btnDecode = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDecode.setGeometry(QtCore.QRect(310, 230, 91, 31))
        self.btnDecode.setObjectName("btnDecode")
        self.grpTable = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.grpTable.setGeometry(QtCore.QRect(550, 0, 261, 441))
        self.grpTable.setObjectName("grpTable")
        self.tblTable = QtWidgets.QTableWidget(parent=self.grpTable)
        self.tblTable.setGeometry(QtCore.QRect(10, 20, 241, 411))
        self.tblTable.setObjectName("tblTable")
        self.tblTable.setColumnCount(4)
        self.tblTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTable.setHorizontalHeaderItem(3, item)
        self.tblTable.horizontalHeader().setDefaultSectionSize(40)
        self.tblTable.horizontalHeader().setMinimumSectionSize(30)
        self.tblTable.horizontalHeader().setStretchLastSection(True)
        self.tblTable.verticalHeader().setVisible(False)
        self.tblTable.verticalHeader().setDefaultSectionSize(20)
        self.tblTable.verticalHeader().setMinimumSectionSize(15)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LZW"))
        self.groupBox.setTitle(_translate("MainWindow", "Text"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Encoded message"))
        self.txtCode.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.lblCode.setText(_translate("MainWindow", "Code:"))
        self.lblDictionary.setText(_translate("MainWindow", "Dictionary:"))
        self.btnEncode.setText(_translate("MainWindow", "v  Encode  v"))
        self.btnDecode.setText(_translate("MainWindow", "^  Decode  ^"))
        self.grpTable.setTitle(_translate("MainWindow", "Table"))
        item = self.tblTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "m"))
        item = self.tblTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "n"))
        item = self.tblTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "c"))
        item = self.tblTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "series"))
